name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Pegando codigo
        uses: actions/checkout@v4.2.2

      - name: Realizando Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Buildando Imagem
        run: echo "Executar Docker Build"

      - name: Enviando Imagem para Docker Hub
        run: echo "Executar Docker Push"

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Pegando codigo
        uses: actions/checkout@v4.2.2
